classes:
  - class: Ingredient
    description: Food ingredients with their properties and safety classifications
    vectorizer: text2vec-transformers
    moduleConfig:
      text2vec-transformers:
        vectorizeClassName: false
    properties:
      - name: name
        dataType: [string]
        description: Name of the ingredient
        moduleConfig:
          text2vec-transformers:
            skip: false
            vectorizePropertyName: false
      - name: safety_class
        dataType: [string]
        description: Safety classification of the ingredient (e.g., controversial, not harmful)
        moduleConfig:
          text2vec-transformers:
            skip: false
            vectorizePropertyName: false
      - name: reason
        dataType: [text]
        description: Detailed explanation of the safety classification
        moduleConfig:
          text2vec-transformers:
            skip: false
            vectorizePropertyName: false
      - name: int_label
        dataType: [number]
        description: Numerical label for classification (0 for controversial, 2 for not harmful)
      - name: prompt
        dataType: [text]
        description: Original classification prompt for the ingredient
        moduleConfig:
          text2vec-transformers:
            skip: false
            vectorizePropertyName: false