classes:
  - class: Ingredient
    description: "A class representing an ingredient with classification data."
    vectorizer: "text2vec-transformers"  # Specifies text2vec-transformers as the vectorizer
    moduleConfig:
      text2vec-transformers:
        pooling: "mean"  # Optional: you can use "mean", "max", or "cls"
        vectorizeClassName: False  # Set to True if you want the class name vectorized
    properties:
      - name: ingredient
        description: "The name of the ingredient."
        dataType: ["text"]

      - name: class
        description: "The classification of the ingredient (e.g., controversial, not harmful)."
        dataType: ["text"]

      - name: reason
        description: "The reason for the ingredient's classification."
        dataType: ["text"]

      - name: int_label
        description: "Numeric label associated with the ingredient's classification."
        dataType: ["int"]

      - name: prompt
        description: "Prompt used for generating insights about the ingredient."
        dataType: ["text"]
