class: ingredients
vectorizer: text2vec-transformers
properties:
  - name: ingredient
    dataType: text
    description: The name of the ingredient
  - name: class
    dataType: text
    description: The classification of the ingredient (controversial, etc)
  - name: reason
    dataType: text
    description: The reasoning or explanation for the classification
  - name: int_label
    dataType: text
    description: The internal label classification
  - name: prompt
    dataType: text
    description: The prompt text associated with the ingredient
